name: buckets
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/buckets?ref=release/1.0.0&depth=1
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
---
name: opensearch
path: git::https://github.com/awslabs/idf-modules.git//modules/opensearch/
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
---
name: efs
path: git::https://github.com/awslabs/idf-modules.git//modules/efs/
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: retention-type
    value: RETAIN
