name: buckets
path: modules/storage/buckets
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
---
name: opensearch
path: modules/storage/opensearch
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: encryption-type
    value: SSE
  - name: retention-type
    value: RETAIN
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: private-subnet-ids
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: PrivateSubnetIds
---
name: efs
path: modules/storage/efs
targetAccount: primary
targetRegion: us-east-1
parameters:
  - name: vpc-id
    valueFrom:
      moduleMetadata:
        group: networking
        name: basic-networking
        key: VpcId
  - name: retention-type
    value: RETAIN
